var Zh = {
    username: "用户编号",
    password: "密   码",
    msg: "出错了",
    submit:"提 交",

    //BonusStream
    TypeID: "奖金类型编号",
    UserID: "用户编号",
    BonusMoney: "奖金金额",
    FeeMoney: "手续金额",
    RealMoney: "实际金额",
    Summary: "奖金描述",
    SummaryEn: "奖金描述",
    InsTime: "时间",
    OrderID: "排序号",
    SttleTime: "发放时间",
    IsSettled: "发放状态",
    FromUserID: "资金来源用户编号",
    IsDel: "删除状态",
    
    //BonusType
    //TypeID:"编号",
    TypeName:"奖项名称",
    TypeNameEn:"英文奖项名称",
    ProcName:"执行存储过程",
    SummaryFormat:"描述格式",
    SummaryFormatEn:"英文描述格式",
    SettleType:"结算方式",
    IsActive:"是否开启",
    Remarks:"备注",

    //MoneyRemit
    BankName:"银行名称",
    BankAccount:"银行账号",
    BankAccountUser:"开户名",
    RemitTime:"汇款时间",
    //InsTime:"提交时间",
    RemitState:"状态",
    MoneyType:"充值币种",
    RemitMoney:"充值金额",
    //YuAmount:"",
    //Remark:"",
    //UserID:"",
    //PassDate:""

    //MoneyStream
    //UserID:"",
    InMoney:"收入金额",
    OutMoney:"支出金额",
    Balance:"账户余额",
    //TypeID:"币种类型",
    //InsTime:"流水时间",
    FromUserID:"来自用户编号",
    IsDel:"删除状态",
    //Remarks:"备注",
    RemarksEn:"英文备注",

    //MoneyStreamType
    TypeName:"类型名称",
    TypeNameEn:"英文类型名称",
    IsActive:"使用状态",
    //OrderID:"排序号",
    //Remarks:"备注",
    //RemarksEn:"英文备注",

    //MoneyTake
    //UserID:"",
    ApplyTime:"申请时间",
    DealTime:"处理时间",
    ConfirmTime:"确认时间",
    TakeMoney:"提现金额",
    Fee:"手续费",
    RealMoney:"实际金额",
    Balance:"现金币余额",
    BankName:"银行名称",
    BankAccount:"银行账号",
    BankAccountUser:"开户名",
    BankBranch:"支行",
    TakeState:"提现状态",

    //MoneyTransfer
    //UserID:"",
    ToUserID:"转账对象编号",
    //TypeID:"",
    MoneyType:"金额类型",
    TransferMoney:"转账金额",
    //InsTime:"时间",
    //Remarks:"备注",

    //user
    UserCode:"用户编号",
    Password: "登录密码",
    ConfirmPassword:"确认密码",
    SecondPassword:"二级密码",
    ThreePassword:"三级密码",
    LevelID:"会员等级",
    RecommendID:"推荐人编号",
    RecommendCode:"推荐人用户名",
    RecommendPath:"直推路径",
    RecommendGenera:"所属代数",//第几代
    ParentID:"安置会员编号",
    ParentCode:"父层用户名",
    UserPath:"层级路径",
    Layer:"所属层数",//第几层
    Location:"注册区域",
    IsOpend:"开通状态",
    IsLock:"锁定状态",
    IsAgent:"代理中心状态",
    AgentsID: "代理中心编号",
    RegTime:"注册时间",
    OpenTime:"开通时间",
    RegMoney:"注册金额",
    BillCount:"注册单数",
    LeftScore:"左区总业绩",
    CenterScore:"中区总业绩",
    RightScore:"右区总业绩",
    LeftBalance:"左区结余",
    CenterBalance:"中区结余",
    RightBalance:"右区结余",
    LeftNewScore:"左区新业绩",
    CenterNewScore:"中区新业绩",
    RightNewScore:"右区新业绩",
    LeftZT:"",
    CenterZT:"",
    RightZT:"",
    RealName:"真实名字",
    NiceName:"昵称",
    Gender:"财主",

    //UserAccount
    UserID:"用户ID",
    BonusAccount:"奖金",
    AllBonusAccount:"累计奖金",
    Emoney:"E币",
    AllEmoney:"累计E币",
    Point:"积分",
    StockAccount:"股票数",
    StockMoney:"购股币",
    ShopAccount:"商城金币",
    BankAccount:"银行账号",
    BankAccountUser:"开户名",
    BankName:"银行名称",
    BankBranch:"支行",
    Province:"省份",
    City:"城市",
    Address:"详细地址",
    IdenCode:"身份证编号",
    Phone:"手机号码",
    QQ:"QQ号码",
    Email:"邮箱地址",
    SafetyCodeQuestion:"密保问题",
    SafetyCodeAnswer:"密保问题答案",

    //UserAgent
    //UserID:"",
    AgentID:"报单中心编号",
    Flag:"状态",
    ApplyMoney:"申请金额",
    ApplyTime:"申请时间",
    OpenTime:"开通时间",
    CloseTime:"结束时间",
    AgentType:"类型",
    PicLink:"图片链接",
    AgentInProvince:"代理省份",
    AgentInCity:"代理城市",
    AgentAddress:"代理详细地址",
    //Remarks:"",

    //UserLevel
    LevelID:"等级编号",
    LevalName:"等级名称",
    RegMoney:"注册金额",
    LevalNameEn:"等级名称-英文",
    BillNum:"单数",
    AwardLevel:"可获奖层数",
    AwardGener:"可获奖代数",
    //IsActive:"使用状态",
    //Remarks:"备注",

    
    //UserUpGrade
    //UserID:"",
    FromLevel:"升级前等级",
    ToLevel:"升级等级",
    ApplyMoney:"支付金额",
    ApplyTime:"申请时间",
    UpGradeTime:"审核状态",
    //Remark:"备注",
    //Flag:"状态",
    Location:"当前位置：首页>>",
    /*页面标题*/
    Registers: "注册页面",
    LoginInformation:"登录资料",
    NetworkInformation: "网络资料" ,
    BankingInformation:"银行资料",
    BasicInformation:"基本资料",
    USD:"元",
    Market:"市场",
    Build: "生成编号",
    detection: "检测编号",
    index:"首 页",
    InformationCenter:"信息中心",
    MemberCenter:"会员中心",
    ShopManagement:"购物管理",
    FinancialQueries:"财务查询"
};
var En = {
    username: "UserName",
    password: "PassWord",
    msg:"Wrong",
    submit: "Submit",
    //BonusStream
    TypeID: "Type ID",
    UserID: "User ID",
    BonusMoney: "Bonus Money",
    FeeMoney: "Fee Money",
    RealMoney: "Real Money",
    Summary: "Summary",
    SummaryEn: "Summary English",
    InsTime: "Time",
    OrderID: "Sort",
    SttleTime: "Sttle Time",
    IsSettled: "Is Settled",
    FromUserID: "From User ID",
    IsDel: "Is Delete",

    //BonusType
    //TypeID:"编号",
    TypeName: "Type Name",
    TypeNameEn: "Type Name",
    ProcName: "Procedures",
    SummaryFormat: "Summary Format",
    SummaryFormatEn: "Summary Format",
    SettleType: "Settle Type",
    IsActive: "Is Active",
    Remarks: "Remarks",

    //MoneyRemit
    //BankName: "银行名称",
    //BankAccount: "银行账号",
    //BankAccountUser: "开户名",
    RemitTime: "Remit Time",
    //InsTime:"提交时间",
    RemitState: "Remit State",
    MoneyType: "Money Type",
    RemitMoney: "Remit Money",
    //YuAmount:"",
    //Remark:"",
    //UserID:"",
    //PassDate:""

    //MoneyStream
    //UserID:"",
    InMoney: "In Money",
    OutMoney: "Out Money",
    Balance: "Balance",
    //TypeID:"币种类型",
    //InsTime:"流水时间",
    FromUserID: "From User ID",
    IsDel: "Is Delete",
    //Remarks:"备注",
    RemarksEn: "Remarks",

    //MoneyStreamType
    TypeName: "Type Name",
    TypeNameEn: "TypeName",
    IsActive: "Is Active",
    //OrderID:"排序号",
    //Remarks:"备注",
    //RemarksEn:"英文备注",

    //MoneyTake
    //UserID:"",
    ApplyTime: "Apply Time",
    DealTime: "Deal Time",
    ConfirmTime: "Confirm Time",
    TakeMoney: "Take Money",
    Fee: "Fee",
    RealMoney: "Real Money",
    Balance: "Balance",
    BankName: "BankName",
    BankAccount: "BankAccount",
    BankAccountUser: "BankAccountUser",
    BankBranch: "Bank Branch",
    TakeState: "Take State",

    //MoneyTransfer
    //UserID:"",
    ToUserID: "To User ID",
    //TypeID:"",
    MoneyType: "Money Type",
    TransferMoney: "Transfer Money",
    //InsTime:"时间",
    //Remarks:"备注",

    //user
    UserCode: "User Code",
    Password: "PassWord",
    ConfirmPassword: "Confirm Password",
    SecondPassword: "SecondPassword",
    ThreePassword: "ThreePassword",
    LevelID: "Level ID",
    RecommendID: "Recommend ID",
    RecommendCode: "Recommend Code",
    RecommendPath: "Recommend Path",
    RecommendGenera: "Recommend Genera", //第几代
    ParentID: "Parent ID",
    ParentCode: "Parent Code",
    UserPath: "User Path",
    Layer: "Layer", //第几层
    Location: "Location",
    IsOpend: "Is Opend",
    IsLock: "Is Lock",
    IsAgent: "Is Agent",
    AgentsID: "Agents ID",
    RegTime: "Register Time",
    OpenTime: "Open Time",
    RegMoney: "Register Money",
    BillCount: "Bill Count",
    LeftScore: "Left Score",
    CenterScore: "Center Score",
    RightScore: "Right Score",
    LeftBalance: "Left Balance",
    CenterBalance: "Center Balance",
    RightBalance: "Right Balance",
    LeftNewScore: "Left New Score",
    CenterNewScore: "Center New Score",
    RightNewScore: "Right New Score",
    LeftZT: "",
    CenterZT: "",
    RightZT: "",
    RealName: "RealName",
    NiceName: "NiceName",
    Gender: "Gender",

    //UserAccount
    UserID: "UserID",
    BonusAccount: "Bonus Account",
    AllBonusAccount: "All Bonus Account",
    Emoney: "Emoney",
    AllEmoney: "All Emoney",
    Point: "Point",
    StockAccount: "Stock Account",
    StockMoney: "Stock Money",
    ShopAccount: "Shop Account",
    BankAccount: "Bank Account User",
    BankAccountUser: "Bank Account User",
    BankName: "Bank Name",
    BankBranch: "Bank Branch",
    Province: "Province",
    City: "City",
    Address: "Address",
    IdenCode: "IdenCode",
    Phone: "Phone",
    QQ: "QQ",
    Email: "Email",
    SafetyCodeQuestion: "Question",
    SafetyCodeAnswer: "Answer",

    //UserAgent
    //UserID:"",
    AgentID: "Agent ID",
    Flag: "Status",
    ApplyMoney: "Apply Money",
    ApplyTime: "Apply Time",
    OpenTime: "Open Time",
    CloseTime: "Close Time",
    AgentType: "Agent Type",
    PicLink: "Pic Link",
    AgentInProvince: "Agent In Province",
    AgentInCity: "Agent In City",
    AgentAddress: "Agent Address",
    //Remarks:"",

    //UserLevel
    LevelID: "Level ID",
    LevalName: "Leval Name",
    //RegMoney: "Register Money",
    LevalNameEn: "Register Money",
    BillNum: "Bill Number",
    AwardLevel: "Award Level",
    AwardGener: "Award Gener",
    //IsActive:"使用状态",
    //Remarks:"备注",

    //UserUpGrade
    //UserID:"",
    FromLevel: "From Level",
    ToLevel: "To Level",
    ApplyMoney: "Apply Money",
    ApplyTime: "Apply Time",
    UpGradeTime: "Approval Status",
    //Remark:"备注",
    //Flag:"状态",
    Location: "Location：Home >> ",

    Registers: "Register Page",
    LoginInformation:"Login Information",
    NetworkInformation: "Network Information",
    BankingInformation: "Banking Information",
    BasicInformation: "Basic Information",
    USD: "USD",
    Market:"Market",
    Build: "Build ID",
    detection: "Detection ID",
    index: "Home",
    InformationCenter: "Information Center",
    MemberCenter: "Member Center",
    ShopManagement: "Shop Management",
    FinancialQueries: "Financial Queries"
};
